require 'mwyerman.options'
require 'mwyerman.keymaps'
require 'mwyerman.plugins'
require 'mwyerman.colorscheme'
require 'mwyerman.cmp'
require 'mwyerman.lsp'
require 'mwyerman.telescope'
require 'mwyerman.treesitter'
