require("mwyerman.settings").setup()
require("mwyerman.neovide").setup()
require("mwyerman.keymap").setup()
-- require("mwyerman.netrw").setup()
require("mwyerman.lazy").setup()
require("mwyerman.terminal").setup()
-- require("nvim-recents").setup()
-- require("statusline").setup()
